t = [{'type': 'Feature', 'properties': {'name': 'Красная площадь, дом 1', 'country': 'Russia', 'country_code': 'ru',
                                        'region': 'Central Federal District', 'state': 'Moscow', 'city': 'Moscow',
                                        'postcode': '109012', 'district': 'Kitay-gorod', 'suburb': 'Tverskoy District',
                                        'quarter': '4', 'street': 'Red Square', 'housenumber': '1',
                                        'iso3166_2': 'RU-MOW', 'lon': 37.6182191, 'lat': 55.7553617,
                                        'formatted': 'Красная площадь, дом 1, Red Square 1, Tverskoy District, Moscow, Russia, 109012',
                                        'address_line1': 'Красная площадь, дом 1',
                                        'address_line2': 'Red Square 1, Tverskoy District, Moscow, Russia, 109012',
                                        'categories': ['catering', 'catering.restaurant'], 'details': [],
                                        'datasource': {'sourcename': 'openstreetmap',
                                                       'attribution': '© OpenStreetMap contributors',
                                                       'license': 'Open Database License',
                                                       'url': 'https://www.openstreetmap.org/copyright',
                                                       'raw': {'name': 'Красная площадь, дом 1', 'osm_id': 6012079979,
                                                               'amenity': 'restaurant', 'osm_type': 'n'}},
                                        'distance': 65,
                                        'place_id': '519a21b0cd21cf424059526732b1afe04b40f00103f9016b0f596601000000920327d09ad180d0b0d181d0bdd0b0d18f20d0bfd0bbd0bed189d0b0d0b4d18c2c20d0b4d0bed0bc2031'},
      'geometry': {'type': 'Point', 'coordinates': [37.61821909999999, 55.75536169968713]}}, {'type': 'Feature',
                                                                                              'properties': {
                                                                                                  'name': 'Остерия Марио',
                                                                                                  'country': 'Russia',
                                                                                                  'country_code': 'ru',
                                                                                                  'region': 'Central Federal District',
                                                                                                  'state': 'Moscow',
                                                                                                  'city': 'Moscow',
                                                                                                  'postcode': '103265',
                                                                                                  'district': 'Kitay-gorod',
                                                                                                  'suburb': 'Tverskoy District',
                                                                                                  'quarter': '18',
                                                                                                  'street': 'Кремлёвский проезд',
                                                                                                  'iso3166_2': 'RU-MOW',
                                                                                                  'lon': 37.61611953680628,
                                                                                                  'lat': 55.7561411,
                                                                                                  'formatted': 'Остерия Марио, Кремлёвский проезд, Tverskoy District, Moscow, Russia, 103265',
                                                                                                  'address_line1': 'Остерия Марио',
                                                                                                  'address_line2': 'Кремлёвский проезд, Tverskoy District, Moscow, Russia, 103265',
                                                                                                  'categories': [
                                                                                                      'catering',
                                                                                                      'catering.restaurant',
                                                                                                      'catering.restaurant.italian'],
                                                                                                  'details': ['details',
                                                                                                              'details.catering',
                                                                                                              'details.contact'],
                                                                                                  'datasource': {
                                                                                                      'sourcename': 'openstreetmap',
                                                                                                      'attribution': '© OpenStreetMap contributors',
                                                                                                      'license': 'Open Database License',
                                                                                                      'url': 'https://www.openstreetmap.org/copyright',
                                                                                                      'raw': {
                                                                                                          'name': 'Остерия Марио',
                                                                                                          'level': -3,
                                                                                                          'indoor': 'room',
                                                                                                          'osm_id': -6228037,
                                                                                                          'amenity': 'restaurant',
                                                                                                          'cuisine': 'italian',
                                                                                                          'location': 'underground',
                                                                                                          'osm_type': 'r',
                                                                                                          'contact:phone': '+7 495 2257488',
                                                                                                          'contact:website': 'www.osteriamario.ru'}},
                                                                                                  'website': 'www.osteriamario.ru',
                                                                                                  'contact': {
                                                                                                      'phone': '+7 495 2257488'},
                                                                                                  'catering': {
                                                                                                      'cuisine': 'italian'},
                                                                                                  'distance': 88,
                                                                                                  'place_id': '513c814601ddce424059d628473bc9e04b40f00101f90145085f0000000000920319d09ed181d182d0b5d180d0b8d18f20d09cd0b0d180d0b8d0be'},
                                                                                              'geometry': {
                                                                                                  'type': 'Point',
                                                                                                  'coordinates': [
                                                                                                      37.61611953680628,
                                                                                                      55.75614109968744]}},
     {'type': 'Feature',
      'properties': {'name': 'Quadrum', 'country': 'Russia', 'country_code': 'ru', 'region': 'Central Federal District',
                     'state': 'Moscow', 'city': 'Moscow', 'postcode': '103265', 'suburb': 'Tverskoy District',
                     'quarter': '2', 'street': 'улица Охотный Ряд', 'housenumber': '2', 'iso3166_2': 'RU-MOW',
                     'lon': 37.6168419, 'lat': 55.7567889,
                     'formatted': 'Quadrum, улица Охотный Ряд 2, Tverskoy District, Moscow, Russia, 103265',
                     'address_line1': 'Quadrum',
                     'address_line2': 'улица Охотный Ряд 2, Tverskoy District, Moscow, Russia, 103265',
                     'categories': ['catering', 'catering.restaurant', 'catering.restaurant.italian'],
                     'details': ['details.catering', 'details.contact'],
                     'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors',
                                    'license': 'Open Database License',
                                    'url': 'https://www.openstreetmap.org/copyright',
                                    'raw': {'name': 'Quadrum', 'osm_id': 3615331573, 'amenity': 'restaurant',
                                            'cuisine': 'italian', 'osm_type': 'n', 'contact:phone': '+7 499 2777100'}},
                     'contact': {'phone': '+7 499 2777100'}, 'catering': {'cuisine': 'italian'}, 'distance': 116,
                     'place_id': '51b8a6e5acf4ce42405934116b75dee04b40f00103f901f5947dd7000000009203075175616472756d'},
      'geometry': {'type': 'Point', 'coordinates': [37.6168419, 55.75678889968768]}}]
